version: '3.8'
services:
  mlops-sandbox:
    build:
      context: .                
      dockerfile: docker/Dockerfile  
    ports:
      - "5000:5000"
      - "8888:8888"
    volumes:
      - ./:/workspace
  minio:
    image: minio/minio
    command: server /data
    environment:
      MINIO_ROOT_USER: admin
      MINIO_ROOT_PASSWORD: password
    ports:
      - "9000:9000"
      - "9001:9001"
